info:
  app:
    name: App Cat
    description: Super App Learning for Cats
    author: Marcio Mafideju Rodrigues
    version: 0.0.1

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, threaddump, mappings
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: mafideju
    password: mancada60
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
    lazy-initialization: true
  security:
    user:
      name: mafideju
      password: 321
