info:
  app:
    name: App Cat
    description: Super App Learning for Cats
    author: Marcio Mafideju Rodrigues
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, threaddump, mappings
  info:
    env:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: mafideju
    password: mancada60
  main:
    lazy-initialization: true
  security:
    user:
      name: mafideju
      password: 321
