info:
  app:
    name: Geo Data Experimental App
    description: Geo Data Experimental App
    author: Marcio Mafideju Rodrigues
    version: 0.1.2

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, threaddump, mappings
  info:
    env:
      enabled: false

spring:
  data:
    rest:
      base-path: /v2
      default-page-size: 10
      max-page-size: 10
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: mafideju
    password: mancada60
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
    lazy-initialization: true
